pipeline {
	agent any
	stages {
        dir('frontend') {
            stage('Build') {
                steps {
                    sh '''
                        npm install
                        npm run build-app
                    '''
                }
            }

            stage('Build Docker Images') {
                steps {
                    sh '''
                        docker build -t udacity-capstone:latest .
                    '''
                }
            }

            stage('Deploy') {
                steps {
                    sh '''
                        docker run --name udacity-capstone -p 8000:80 -d udacity-capstone:latest
                    '''
                }
            }
        }
	}
}
